environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - fast_finish: true
         platform: 'x86'
    
    - fast_finish: true
         platform: 'x64'
             
install:
  - choco install -r -y mingw
  - choco install -r -y ninja
  - "SET PATH=C:\\MinGW\\mingw32\\bin;C:\\MinGW\\bin;%PATH%"

branches:
  # whitelist
  only:
    - master
     

build_script:
  - cmd: echo Running cmake ...
  - mkdir build
  - cd bin
  - cmake --version
  - if "%platform%"=="x86" ( echo ' its x86' ; echo ' is x86' )
  - if "%platform%"=="x64" ( echo ' its x64' ; echo ' is x64' )
#  - dir  C:\MinGW\bin
#  - dir  C:\MinGW\mingw32
#  - mingw32-make   NFsim

#  - mingw32-make --version  
  
artifacts:
  - path: bin\NFsim.exe
    name: NFsim
  
#deploy:
#  provider: FTP
#  protocol: ftp
#  host: ftp.midcapsignals.com/midcap/d_appveyor
#  username: roberthclark
#  password:
#  secure: K22E4pSAup6/htlGmoSBMw==
