environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - generator: "Ninja"

install:
  - choco install -r -y mingw 
  - choco install -r -y ninja
  - "SET PATH=C:\\tools\\mingw\\bin;%PATH%"

branches:
  # whitelist
  only:
    - master
    - release
    - mcell
    - release-windows
    
platform: Win32


build_script:
  - cmd: echo Running cmake ...
  - mkdir build
  - cd build
  - cmake -G "Ninja" ..
  - ninja

artifacts:
 - path: build\NFsim.exe
   name: NFsim

notifications:
  - provider: Slack
    auth_token:
      secure: jN4Fas2b8/Z1yNInrC6yWZf1sHzA5M7M/wANf+O4nRQLRqNqLsmNFGMNusaS+adFyS0kz3TfGBtLjAEKeh84jw==
    channel: build-results

deploy:
  - provider: gcs
    access_key_id: GOOGHK4SCMDVVDNXWLUF 	
    secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
    bucket: appveyor-rhclark-nfsim
    skip_cleanup: true
    local_dir: dist

