environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - fast_finish: true

install:
  - choco install -r -y mingw
  - "SET PATH=C:\\tools\\mingw64\\bin;%PATH%"

branches:
  # whitelist
  only:
    - master
     
platform: Win32

build_script:
  - cmd: echo Running cmake ...
  - mkdir build
  - cd build  
  - cmake --version
  - mingw32-make --version  
  - cmake  ..  
  - mingw32-make  
  - dir  C:\projects\nfsim\build


artifacts:
 - path: build\NFsim.exe
   name: NFsim


deploy:
  - provider: gcs
    access_key_id: GOOGHK4SCMDVVDNXWLUF 	
    secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
    bucket: appveyor-rhclark-nfsim
    skip_cleanup: true
    local_dir: dist

