environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - platform: x86
      fast_finish: true
    
    - platform: x64
      fast_finish: true
      generator: "Ninja"

             
install:
  - choco install -r -y mingw
  - choco install -r -y ninja
#  - type C:\ProgramData\chocolatey\logs\chocolatey.log
#  - "SET PATH=C:\\MinGW\\mingw32\\bin;C:\\MinGW\\bin;%PATH%"

branches:
  # whitelist
  only:
    - master
     

build_script:
  - cmd: echo Running cmake ...
  - mkdir build
  - cd bin
#  - cmake --version
  - if "%platform%"=="x86" ( "SET PATH=C:\\MinGW\\bin;%PATH%" )
  - if "%platform%"=="x86" ( "SET PATH=C:\\MinGW\\mingw32\\bin;%PATH%" )
  - if "%platform%"=="x64" ( "SET PATH=C:\\MinGW\\bin;%PATH%" )
  - if "%platform%"=="x64" ( "SET PATH=C:\\MinGW\\mingw64\\bin;%PATH%" )
  - if "%platform%"=="x86" ( "mingw32-make   NFsim" )
  - if "%platform%"=="x64" ( "cmake -G "Ninja" .. ; ninja" )
#  - dir  C:\MinGW\bin
#  - dir  C:\MinGW\mingw32
#  - mingw32-make   NFsim

#  - mingw32-make --version  
  
artifacts:
  - path: bin\NFsim.exe
    name: NFsim
  
#deploy:
#  provider: FTP
#  protocol: ftp
#  host: ftp.midcapsignals.com/midcap/d_appveyor
#  username: roberthclark
#  password:
#  secure: K22E4pSAup6/htlGmoSBMw==
