environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - fast_finish: true

install:
  - choco install -r -y mingw
  - "SET PATH=C:\\tools\\mingw\\bin;%PATH%"

branches:
  # whitelist
  only:
    - master
     
cache:
    - i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    
platform: Win32


build_script:
  - cmd: echo Running cmake ...
  - mkdir build
  - cd build  
  - cmake --version
  - cmake  ..  --target all
  - dir


artifacts:
 - path: build\NFsim.exe
   name: NFsim

notifications:
  - provider: Slack
    auth_token:
      secure: jN4Fas2b8/Z1yNInrC6yWZf1sHzA5M7M/wANf+O4nRQLRqNqLsmNFGMNusaS+adFyS0kz3TfGBtLjAEKeh84jw==
    channel: build-results

deploy:
  - provider: gcs
    access_key_id: GOOGHK4SCMDVVDNXWLUF 	
    secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
    bucket: appveyor-rhclark-nfsim
    skip_cleanup: true
    local_dir: dist

