environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - platform: x86
      fast_finish: true
    
    - platform: x64
      fast_finish: true
      generator: "Ninja"

             
install:
  - choco install -r -y mingw
  - choco install -r -y ninja
#  - type C:\ProgramData\chocolatey\logs\chocolatey.log
#  - "SET PATH=C:\\MinGW\\mingw32\\bin;C:\\MinGW\\bin;%PATH%"

branches:
  # whitelist
  only:
    - master
     

build_script:
  - cmd: echo Running cmake ...
  - cmd: mkdir build
#  - pwd
#  - cmake --version
  - if "%platform%"=="x86" ( SET "PATH=C:\\tools\\mingw32\\bin;C:\\MinGW\\mingw32\\bin;C:\\MinGW\\bin;%PATH%")  
  - if "%platform%"=="x86" ( move CMakeLists.txt      CMakeLists.x64.txt )
  - if "%platform%"=="x86" ( move CMakeLists.x86.txt  CMakeLists.txt )
  - if "%platform%"=="x86" ( cd build )
  - if "%platform%"=="x86" ( cmake -G "Ninja" .. )
  - if "%platform%"=="x86" ( ninja )
  - if "%platform%"=="x86" ( mv NFsim.exe  NFsim.win32.exe )
  - if "%platform%"=="x86" ( cd .. )
  - if "%platform%"=="x86" ( perl .make_tar.pl  --platform x86 )
  - cmd: dir  ./build )
  
  - if "%platform%"=="x64" ( SET  "PATH=C:\\tools\\mingw64\\bin;%PATH%" )
  - if "%platform%"=="x64" ( cd build )
  - if "%platform%"=="x64" ( cmake -G "Ninja" .. )
  - if "%platform%"=="x64" ( ninja )
  - if "%platform%"=="x64" ( mv NFsim.exe  NFsim.win64.exe )
#  - dir  C:\MinGW\bin
#  - dir  C:\MinGW\mingw32

  
artifacts:
  - path: '.\build\NFsim.win*.exe'
    name: NFsim
  
  - path: '.\build\NFsim-source-win*.zip'
    name: NFsource
  
deploy:
  provider: FTP
  protocol: ftp
  host: ftp.midcapsignals.com/midcap/d_appveyor
  username: roberthclark
  password:
    secure: K22E4pSAup6/htlGmoSBMw==
  artifact: NFsim 
