environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - generator: "Ninja"

install:
  - choco install -r -y mingw
  - choco install -r -y ninja
  #- "SET PATH=C:\\tools\\mingw32\\bin;%PATH%"
  - "SET PATH=C:\\tools\\mingw32\\bin;C:\\MinGW\\mingw32\\bin;C:\\MinGW\\bin;%PATH%"

branches:
  # whitelist
  only:
    - master
    - release
    - mcell
    - release-windows
    
platform: x86


build_script:
  - cmd: echo Running cmake ...
  - mkdir build
  - cd build
  - cmake -G "Ninja" ..
  - ninja

artifacts:
 - path: build\NFsim.exe
   name: NFsim

#notifications:
#  - provider: Slack
#    auth_token:
#      secure: jN4Fas2b8/Z1yNInrC6yWZf1sHzA5M7M/wANf+O4nRQLRqNqLsmNFGMNusaS+adFyS0kz3TfGBtLjAEKeh84jw==
#    channel: 'build-results'


#deploy:
#  provider: FTP
#  protocol: ftp
#  host: ftp.midcapsignals.com
#  username: roberthclark
#  password:
#    secure: K22E4pSAup6/htlGmoSBMw==
#  folder: midcap/junk
#  artifact: /NFsim.exe/      

#deploy:
#    # Amazon S3 deployment provider settings
#  - provider: S3
#    access_key_id:
#      secure: gyxTxeHww7ldSGxRSqjkAA1qa2JodkLDtmZeVrdmPfA=
#    secret_access_key:
#      secure: qbD+jQk8IRRrHhucUlL6D17o4DffrAObRzBlo1ll8NzHG09o2kCGskQzd828WLJD
#    bucket: nfsim
#    folder: 1.12.1
#    artifact: nfsim
#    set_public: true
#
