environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - fast_finish: true

install:
  - choco install -r -y mingw-w64
  - "SET PATH=C:\\MinGW-W64\\mingw64\\bin;C:\\MinGW-W64\\bin;%PATH%"

branches:
  # whitelist
  only:
    - master
     
platform: x64

build_script:
  - cmd: echo Running cmake ...
  - mkdir build
  - cd bin
  - cmake --version
  - dir  C:\MinGW-W64\bin
  - dir  C:\MinGW-W64\mingw32
  - mingw64-make  NFsim
#  - mingw32-make --version  
  
artifacts:
  - path: bin\NFsim.exe
    name: NFsim
  
deploy:
  provider: FTP
  protocol: ftp
  host: ftp.midcapsignals.com/midcap/d_appveyor
  username: roberthclark
  password:
    secure: K22E4pSAup6/htlGmoSBMw==
    
