environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - fast_finish: true

install:
  - choco install -r -y mingw
  - "SET PATH=C:\\mingw\\mingw32\\bin;C:\\mingw\\bin;%PATH%"

branches:
  # white list
  only:
    - master
     
platform: x64

build_script:
  - cmd: echo Running cmake ...
  - mkdir build
  - cd bin
  - cmake --version
  - dir  C:\mingw\bin
  - dir  C:\mingw\mingw32
  - dir  C:\tools\mingw32
  - dir  C:\tools\mingw64
  - make  NFsim
#  - mingw32-make --version  
  
artifacts:
  - path: bin\NFsim.exe
    name: NFsim
  
deploy:
  provider: FTP
  protocol: ftp
  host: ftp.midcapsignals.com/midcap/d_appveyor
  username: roberthclark
  password:
    secure: K22E4pSAup6/htlGmoSBMw==
    
