os:
- osx

compiler:
  - clang
language: c++
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - python-dev
    - python-numpy
    - libxml2-dev
    - libboost-all-dev
    - cmake



after_success:
- source set_tags.sh

notifications:
  email: true
  slack:  faederlab:l0waIGp58v8ZV74N7QmXGoWs
  
before_install:
- source osx_install.sh

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi


script: 
  - mkdir -p build; mkdir -p dist; cd build; cmake ..; make; cp NFsim ../dist; cd ..; 
  - cd validate;tar xfj bionetgen-2.2.6.tar.bz2
  - python validate.py
  - cd ..
before_deploy:
- cd dist; python changeFilename.py; cd ..


#
#deploy:
#  provider: gcs
#  access_key_id: GOOGHK4SCMDVVDNXWLUF 	
#  secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
#  bucket: travis-rhclark-nfsim
#  skip_cleanup: true
#  local_dir: dist
#  on:
#    all_branches: true


#deploy:
#  provider: releases
#  user: rhclark
#  password: DqgNc5GyYgzr2RLXNiw5YNXKASSh5mK1diVItvx3Q89KAnsgwYf0pHzKHqaOwMjlMfKDcQkWiVh6LckajuoERbyo8OeE1PslwGVxujm7Bdpt5sM5yXo6EPwro52Nmr/Z9XUN9mFzLlUuH/KQu9XVZ6ObDojFtYSw9eWcoKuFvUKL1ABEGW1QjKee0rBR4zXK20rgsY5P0BfQZ0MFZIAGPi6pxAg4IJWw9Awsrv08FDOSqiIqvxdoiZleTO6Cj9RTYjSIsQCDG5n2DlLOEV0RfYoFxIumN9LNrVM/ZAMU2fo6pEMwCo+LvkOQYXBLzNGG5+th+f323de0t8clDvLAmnyek5ZoV4qf/1s2oEOVpuYKhVbD9/ndbaA0HL65PmrFl5OVNd6+uXrnrxaYDM0JV2C+mMLHD1CPCQGVmDeg7nRhN3p7co2gIoL0ckQT8yLgKBLIjBHDl9ZqMsY2PbqM27tZGBWuOg9h/eFgSxktjwuNT6f4Qe779yulIWl0bx3MpNqwV4/VmHklOz8NEPUiaT+efmCCUuQseTmwPtpOsIvBKOLpQbX0QWAVAJ6irJ6uGzSHZqQQ4J11HzRG0/hxqxA1cQjoS9trX47x1QRBf/O3r7uJtoG00dNr5XBamlBUKffzgTj68d9nmeUhvKHaNpuNb21KnW+9kuQkZRcCrT8=
#  file: ../dist/NFsim
#  file_glob: "true"
#  skip_cleanup: true
#  on:
#    branch: master
#    repo: rhclark/nfsim
 
