os:
- osx

compiler:
  - clang
language: c++
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - python-dev
    - python-numpy
    - libxml2-dev
    - libboost-all-dev
    - cmake

#env:
#  global:
#    - secure: "CaFXoGwNrWNp8Zq9zHSDKPGJLbEFz2jNqdPLrKUc6xp2AfhRxe3JTZYEj/bko4yGbyPXcp0VybmN1U/jgzuV/czLS+ZsQtZ7X2OtM3v/f+SEMQ/aK65VSgoaVHqvLLBN69vM/3SZQDzjSNF5yMDbbCVBXPrTg15aiUJLXjPbzzUqTcvBe4pYscugpHV5EsVyNQm8gQc2jkIxfGxif94qeTGWM78fU8OhcSdUoC0H/oZdu7thSLynQcICZbPtYAz5H4373GY5sQkSrHS/uuhLRl8OY+5hs2vbOKvehjX3JkjUTfbAKRTJg0KQrSIKLLzCrv/uxNlsIeDmhgRx5kxrcFMFPdYLeQXSbTuRTuQzjK2uIDHXMfEvNmUV4chFCrn8W7uG3RYzs3vfShh9YEmUd4uhjXK+AUSpgk6S+3iQeJE9dFBZUc+1IhtkJlpd8+V+U03B5c4eWG2kVM+Px0OSP6AejcuYBVoDNEJRzx8U+jYrMZ1sGadgXB3/dh+7CMpqPi9qdGcNSFoUnxjZfsfKvzzM64+L2cflm9y9TJX1+DRXvTRyQmxjpaWD0odm0703XQwo1q10QDBscWNSWbdNcLP8rvS2ZGX8K2p9Y5/c8GylOnwwG9WLWc1dsuzH/EMzyIvErK5Xy3cD7XWNM43ejajTKuCDRgiG165Ni8b0N2c="
#    - secure: "RIxzTbcROPaRtW5CVmvHrV31FWmcvm/IySuXiRwGgZcH9MRkHx0nNRj6R796L01PdGlC3t/ezkCOpR6pXd2ynGiKsiGdWh5unriiO37sNqDukV1cjQj3y5ZoxDoxKaJvql2UQUtDsFPaM3BiQeKUbv6VAXLlgglNyWgxrInbIeJZbKbpPZIiZN1uhZtbKWZ4yu+/zhN5JcLSUocbmvBSokjW60y/D6Q+I5ji0lRFvQ7vQdqPXmWBlOyLan4lg792yk/UZnJeiyB78apl8yFNVNCnFo+shYKWpKQVePL6/+HbC9XTy+V6SO4O5l7f520hmV4A2Dbw1AenvGd5MrrQ05llJXnovxam9UJqZWWe2/kMVZ1oEDbcKy2gfcH+yCJrCl5XGD9Zv2J28o/YeIdP6vWy0jgRMZccILiZVde7RJpX/z4VXWeEKBYNC+qppo5AS8ROxZs7FDYVJrm85/GOBzyvmEeXR9P/I+dEqk5vKxyRznUag5DCDLbfaLLABSwY99BUZSSfDdC+nEUz+2H59QNrz8EhM0xf2vmyDYdH+VeV9bJyniZSLzVY3p/aR9XDTR1AgnKOwXDEhJ6lO+gcGH1ZFzuLRiLBk310RfRTvI1+zXB6fukKWj/DDndhH2wFjdsiC2ep36dKEEbVcxD1aZIsT28yC0i9gb1UmIzDeMM="
#    - secure: "hu1VTTSY4U1hdoBPQqtaMm7Mj6dSma40/6/zgxk++/hoNBqsBSp1AxeP1EaYwVTmv+IhWH/mcU2sP9t29nL+Ueear0zECx9msbzFq6QMSwFvvao7KuCx4HYBgEtniSEKpLgDPA+imwD3OrkXtQiE3L3yYK1BMYhvWntAW1IXaB/GdhtBHJnGQhjIgHsfkJ2cFKmEu5f3UcDa807uAo2kNQuHn+kW3eC3MOksMFPqzADOC3U4FB0lsLt5Tkhz3lXwNXK8nqE73V0HT4sudVqdR7kyNu6/vhDoLRWgJXuwH4wmB4vhQ5ZE2HohnKWEKu64DTSCNiBjKI4Tz17TyMhbGnfZMWIUnE6Ko56ihRPwtMtmMZQz0GVfepMPMuXbpwx5zvwnJmah5q3x3V/HmZNEF9/craJMVoicPmiZBYkwtl2xMAt/RJHXkKPzlZxLNyOrWAlYoT/xjOjX1zHNaeCpzPJjzNgA+ftcRVXfcLjb6UGhITXlTMu7OCTkwNIDAonq5YtwMKB0PAQBkBeW49I3jI3ue2c+ZObNwOZuPnFvr7xWOE94MNON6e/12f71cKpt0bITHDK5lAl3Sdq8NjFH1GAiLsVULB2Xsa3sJtFeiJrgLGbDldR6eEFeX6qrzhhfnLQAlmNZ8LcK6xS6CObwTUOPvugBBybCl8+KFbqBtRo="
#    - secure: "nfMc2bqTKlr1kNq/zK7PyJcF0tHVSOj2/Z0wWu5nke41f+CFJIc9Aznr4tFAytRzOxi8A0HHZRSA2yDyfAshAj3d2sxO74PsBFChnHYFxNx0pzQMmHyWNaEKrSZdABRSxW0h2d8PJto0o/CKmzQZBNPc92xqQj6jB8Cu3N988QHysP5np7/27YD1KAi252dZ6ciVEhNzNrGeBLvFQvNnvMEczY52QY8mApzkHSNdihWT+AK8Sq7M8Aus9OyYsP1V4PcAUYJz4QcerBEL39lgX+AInSdOSpu/W8p/ale/CuEVP7727xnjbkJmX7YHud6e7K5SEZ3caJIA3ajdFVkSfIWbqd5SJkYvb10Mh0xCIWtOhh50E+db0/qUDEVap1POkunP54YR68MzkK2tyQc0qZ8rcVYYSqVoepSQNGMKUv0R5D371JqUuzxj/cj6+fnZmHLWXD4jIikuRmrLuZVlrrW5P0jsAlBvD9TD8KfmTvgQH8DPXKGEeWX1Jm37GqHKRy48femW67LN5D0zYlHQGQSVS5CRKI1CHlA7JnSxaUshO1WlcV3yTVbepQsxIqjJEvoO8bFW78ki6zFtISpwbEpCpyGdLTDzVp7NRIzQo5vHATNs4bYHqduGdwnXsPgIU5sPCyvMpijBWux4Es8L6u58RQANLtT1xHaEvbVd6pg="



#   To create these passwords, you will need to use the   travis   command line tool.  It needs to be downloaded from the
# web and installed.  I believe that it has Ruby as a prerequisit.  These two travis commands were used to generate the 
# passwords below:
#   travis encrypt FTP_USER=<username>     --skip-version-check -r rhclark/nfsim
#   travis encrypt FTP_PASSWORD=<password> --skip-version-check -r rhclark/nfsim
env:
  global:
    - secure: "Kda7YvWhefM1q8lK4bNvm7szNJD3Z0VEGYMWIT7lHv7P18jnYu/o+5zrhX3mt5vNffsK/Vhr4rPncw/MJQdRNME3XwYcP06xzHUdrwsUbg6zy4CmTITMgWkO0FTGPX7oJjSMpRUCC7uFBV74LjiLgw7PSyGlbJyPog76tiketNQTbMIfals49syErP+TfvM2UtxqjhvMG5MO73syt3pJ/63uV1j+ke4jY9l4x1U8w3XS9c6IsvDv+J0aHBNehvU6TDlkaC9EDJ4K7HJs4OkrtN1A2pmLiOGKaRncAeRs/Ptj9sk2kLEe6g9GAFe+woD4YrAxyCw69gDCpRRTiSpk+VO+MvCKdA4bu4snK4McXm+SqnYqEhbcSc0d/orlsGFJMOP8zFp1hKYDZTJbpxSW6TFyg/3nfRQfK1wj0Bwnrg6A+S6tIRXZPKlTaj+RqLqucLw2WinPR0s1jP7zi2cvh1ZWsiCSjpP8RdJ41WMKmGRFtHH5DPkJZa6KYWVpZqZsMYYxiKVLGlIFoPmNs/LIGGi00nsgZRSQmlTeyRWxV7+fCuj5SlkOIFh7O0kfxku7merL8FUoqH+Pl0wyvRiDP9gj0lvjeirvI1bwGKtPNyn5MAjpf4NMBg/sjdT12uPz8XUrNZZGYV/XuHXd/U/4B3StGMWapWMjnuPLjLsVbhs="
    - secure: "hm1QdjgMrjPhaYTaCVb/dkSPTTFzF0RAMs3a6EQAtvYMZCoJbyxZtzkvQ5oYO3ez5j2rbXaxDEQ/mWMn/DMx3hwvPR7Fu+w1KqIL4FlbS5PZO4Bs7Jo+lMU2f6Wl2O99aGUJ8NAoowTWgg0kgss0U5HfvK4++3S6Oh7x58OWjM7uynqVe8/hzvkLOyWfFITWXkPZwgOcyaZX5E+H/uYcQjmaGYr4TV3CLn3lB3IhBYSb+Apo39gXwB0K5yWXpLIEuINxsTveVVMeEunSII4HpNT/C67+fduGhWBy4d4lYjBTLiuS7mAyfoeJK9lIsVd3H5MKRIHRw0ORKUDPEmak0mmFCGOm0W5LALgyiaSSkKt6T/NDPn4coFDwh8pRT149NNZOto0A830DfcuR8mh4ZbyI9kYGnJVrhM2fhNNGmtsdcnBxi0UzZmmGl+YchaBdb3wS+j7SX+uSvxT9aUD1W8XZ+Whpubpf8YwYBLEPxtOcY596+4enu4fEVtSqJpOcRqQzyS2FP8k5mFaRblLd230RbTkR99TrGxHVVdeOGirpUCIpowlnt56DXMmfD3R7s797RZYTJx1elZBMGbaxruzIwhsEDBOWgOfO8GXuXcrua7xjzb8ChcliWtp3crdxUtZ4T6lc77/VstatafP2YnhBXr9+yUPnJyzJ/jzrAK4="

#notifications:
#  email: true
#  slack:  faederlab:l0waIGp58v8ZV74N7QmXGoWs
  
before_install:
- source osx_install.sh

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    
before_script: 
  - git config --global user.email "rhclark.pitt@gmail.com"
  - git config --global user.name  "Robert Clark"
#  - git remote rm origin
#  - git remote add origin https://rhclark:${GH_TOKEN}@github.com/rhclark/nfsim.git

script: 
  - mkdir -p build; mkdir -p dist; cd build; cmake ..; make; cp NFsim ../dist; cd ..; 
  - cd validate;tar xfj bionetgen-2.2.6.tar.bz2
  - python validate.py
  - cd ..
#  - git config --global credential.helper "store --file .git/credentials"
#  - echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials
#  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials

#after_script:
#  - node ./node_modules/grunt-cli/bin/grunt release

after_success:
  -  "curl -T ./dist/NFsim -u $FTP_USER:$FTP_PASSWORD ftp://ftp.midcapsignals.com/midcap/junk/"
  -  cd dist; ls -lt  
#  - cd dist; python changeFilename.py; cd .. ; pwd



#    "curl -T index.html -u $FTP_USER:$FTP_PASSWORD ftp://wecodetheweb.com/public_html/"

#after_success:
#  - source set_tags.sh
 

#before_deploy:


#
#deploy:
#  provider: gcs
#  access_key_id: GOOGHK4SCMDVVDNXWLUF 	
#  secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
#  bucket: travis-rhclark-nfsim
#  skip_cleanup: true
#  local_dir: dist
#  on:
#    all_branches: true

# A good link:
#   http://szagurskii.com/blog/how-to-deploy-apk-to-github-releases-with-travis-ci/

#deploy:
#  provider: releases
#  api_key:
#    secure: ${GITHUB_API_KEY}
#  file: 
#    -  "./dist/NFsim"
#  file_glob: "true"
#  skip_cleanup: true
#  on:
#    repo: rhclark/nfsim
#    tags: true

